services:
  app:
    container_name: javacode_fastapi_app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app:/app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - ${DB_SERVICE}
      - ${TEST_DB_SERVICE}
      - ${REDIS_SERVICE}
  db:
    image: postgres:13
    container_name: javacode_postgresql_prod_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test-db:
    image: postgres:13
    container_name: javacode_postgresql_test_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${TEST_NAME}
      - POSTGRES_USER=${TEST_USER}
      - POSTGRES_PASSWORD=${TEST_PASSWORD}
    ports:
      - "${TEST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis-app:
    image: redis:6
    container_name: javacode_redis
    ports:
      - "${REDIS_PORT}:6379"
volumes:
  postgres_data: