services:
  app:
    container_name: javacode_fastapi_app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./app:/app
    depends_on:
      - db
      - test-db
      - redis-app
  db:
    image: postgres:13
    container_name: javacode_postgresql_prod_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ", "${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  test-db:
    image: postgres:13
    container_name: javacode_postgresql_test_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${TEST_NAME}
      - POSTGRES_USER=${TEST_USER}
      - POSTGRES_PASSWORD=${TEST_PASSWORD}
    ports:
      - "${TEST_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ", "${TEST_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis-app:
    image: redis:6
    container_name: javacode_redis
    ports:
      - "${REDIS_PORT}:6379"