[tool.black]
line-length = 120
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 120
known_third_party = ["flask", "requests"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[tool.flake8]
max-line-length = 120
ignore = ["E203", "E266", "E501", "W503"]
exclude = [
    ".venv",
    "__pycache__",
    "build",
    "dist",
]