"""create wallets

Revision ID: c0e0ff1ca1a6
Revises: 
Create Date: 2024-10-05 18:10:01.292171

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0e0ff1ca1a6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet",
        sa.Column("balance", sa.Numeric(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("balance >= 0", name="check_balance_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallet_id"), "wallet", ["id"], unique=False)
    op.create_table(
        "wallet_history",
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column(
            "operation_type",
            sa.Enum("DEPOSIT", "WITHDRAW", name="operationtype"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallet.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallet_history_id"), "wallet_history", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallet_history_id"), table_name="wallet_history")
    op.drop_table("wallet_history")
    op.drop_index(op.f("ix_wallet_id"), table_name="wallet")
    op.drop_table("wallet")
    # ### end Alembic commands ###
